### ISSUE TITLE
Is anyone interested in this?

### ISSUE THREAD

**Issue by eljojo** [ruby-in-the-park/ruby-in-the-park#1]
Is anyone interested in gathering together in a park and having a nice afternoon?
What date works for you?

The basics are a weekend with ideally nice weather.

**Comment by rin** [comment]
:sunny: :deciduous_tree: :strawberry: 

I'd be in. But since the date heavily depends on the weather, and weather forecasts are not exactly reliable, I think it would be easiest to organize the date via twitter (max. 2 days in advance).

**Comment by bitboxer** [comment]
I am interested, too. :+1:  . Sadly the weather is not that reliable in April. We need to check the date max 2 days in advance. But the rest can be planned just to be prepared for when it's :sunny:

**Comment by eljojo** [comment]
@rin @bitboxer totally agree.
I think a nice way of working is people "watching" the repository, so they get new notifications whenever a new issue is opened. And for every meetup we open an issue.

I guess for the time being we could keep this issue open just to see how many people are interested and if everyone has suggestions they could write them here or open a pull request to the main readme.

**Comment by skade** [comment]
@eljojo you mean, in the soup of other GH notifications? :)

I would be in, but April is a tough month for me.

**Comment by eljojo** [comment]
@skade fair point. Maybe a mix of twitter and github would do the trick.

**Comment by txus** [comment]
I'm in!!!! :shipit:

**Comment by phansch** [comment]
This sounds like fun, count me in! :+1:

**Comment by hagenburger** [comment]
I would be in. But it should be slightly warmer than today :)

**Comment by sheley** [comment]
i have a hacky sack and i will bring it. saturdays are better than sundays for me. also, tempelhof.

**Comment by bitboxer** [comment]
I have a few frisbees&copy; aka flying discs I can bring along

**Comment by rin** [comment]
+1 for Tempelhofer Feld!

**Comment by schultyy** [comment]
Jan is in as well

**Comment by pxlpnk** [comment]
I would be in too.

**Comment by asaaki** [comment]
:+1: Let's have fun in da park! :palm_tree: :sunny:

**Comment by ctrlaltjustine** [comment]
I'd be in but I'll be back in the states April 5 - probably end of May.

**Comment by myabc** [comment]
:+1: 

Doodle probably works better than GH for picking a date.

**Comment by stefanozanella** [comment]
Count me in as long as it's not in the first weekend of April. I agree though that GH might not be the best channel to ensure people are updated. Maybe set a twitter hashtag as well?

**Comment by skade** [comment]
By the way, there are quite a few parks where you can grill.

**Comment by ellenkoenig** [comment]
Would  be in, too. And I second the suggestion for using Doodle to figure out who can join when :)
http://doodle.com/en/

**Comment by xamebax** [comment]
+1 +1 +1! I'm all for almost any weekend, I sometimes travel, but that's not really important. I second the idea of tempelhofer feld and have not one, but two (!) blankets.

**Comment by nanoparsec** [comment]
I am in, too. And I can use our Rails Girls Berlin channels for spreading the word.

**Comment by KathleenLD** [comment]
I'm in if we do this late May, but I'm also open to joining for whenever the next iteration happens!

**Comment by eljojo** [comment]
ok leute, let's do this! head to: #2
