### ISSUE TITLE
When?

### ISSUE THREAD

**Issue by eljojo** [ruby-in-the-park/ruby-in-the-park#2]
Hi everyone,
it's been a long time since I haven't updated this. Lots of work and whatnot.
but **guess who's back?**

I'm going on vacations for a week and when I come back I'll have lots of time to organize this, so the question remains: **when do we do this?**

Just opened a **doodle [here](https://doodle.com/psb73zrdkzmtxdbq)** and I guess the day with the most people will be the winner one.

Feel free to comment something here.

Oh, btw, @malwine spent some time making this awesome new logo!
![Ruby in-the-park](https://raw.githubusercontent.com/ruby-in-the-park/ruby-in-the-park/master/logo.png?ab2bf9ccd67ec744296d8a0ce66c62ac376f4e14)

**Comment by bitboxer** [comment]
Your doodle link is not working :sob:

**Comment by bitboxer** [comment]
BUT I love the Logo! @malwine awesome job!

**Comment by eljojo** [comment]
@bitboxer just opened the doodle, the link is working now. https://doodle.com/psb73zrdkzmtxdbq

**Comment by myabc** [comment]
@malwine LOVE IT!

**Comment by eljojo** [comment]
btw feel free to suggest more dates/time etc in doodle

**Comment by Malwine** [comment]
@myabc @bitboxer thank you :blush:

**Comment by skade** [comment]
I am missing the "I just fell out of a plane from UY and might join late and very jetlagged" option for the 25th.

**Comment by schultyy** [comment]
The Logo is awesome

**Comment by myabc** [comment]
Let's make a decision!

**Comment by eljojo** [comment]
ok, a week has passed by and the date has been chosen: the picnic will be the **1st of June**. It will be in **Tempelhofer Feld**, I still need to figure out where exactly.
Just added an [iCal link](https://raw.githubusercontent.com/ruby-in-the-park/ruby-in-the-park/master/ical.ics?87eddf7be877d2e72b67dc3d938008e48b3d241e) (right click and save-as `something.ics` will do the job).
I'll keep people updated on twitter and on the readme file.
