### ISSUE TITLE
weather on Sunday, June 1st

### ISSUE THREAD

**Issue by andreiursan** [ruby-in-the-park/ruby-in-the-park#3]
Weather is hard to predict, right now it doesn't look very good for next Sunday.
http://www.weather.com/weather/tenday/GMXX0007

Might be a good idea to reschedule the event if weather does not change in good until Fri/Sat. Otherwise picnic + rain does not sound too "DRY".

**Comment by eljojo** [comment]
I was just thinking the same today. 
I'll pay close attention and otherwise re-schedule. 

Thanks for the notice. 
By Thursday we should probably have a better perspective.

**Comment by eljojo** [comment]
Let's continue the discussion on #3.
I'd say, let's do it on June the 1st.
