### ISSUE TITLE
First Picnic

### ISSUE THREAD

**Issue by eljojo** [ruby-in-the-park/ruby-in-the-park#4]
Hi Picnic-ers,
I'm opening this issue to discuss everything related to the first Picnic.
### Time and Location

``` ruby
@picnic.location = GeographicPoint.new(%q{52°28'47.7"N, 13°24'18.9"E})
```

Meeting time: **3PM**
Location: Tempelhofer Feld 

In Tempelhof there's **two** BBQ Areas, the picnic will be held in the **BBQ Area Closest to the Baseball Area**, not the one next to the garden.

[Google Maps Link](https://www.google.com/maps/place/52%C2%B028'47.7%22N+13%C2%B024'18.9%22E/@52.4799501,13.4015292,15z/data=!4m2!3m1!1s0x0:0x0) | [Apple Maps Link](http://maps.apple.com/?lsp=7618&sll=52.479917,13.405250&q=52.479917,13.405250)
![screen shot 2014-05-31 at 14 24 12](https://cloud.githubusercontent.com/assets/491230/3138976/84c131ba-e8be-11e3-9c00-9f13ef682d33.png)
### Contact or questions

``` ruby
@picnic.contact_person = User.find_by(email: 'jojo@eljojo.net')
```

You can reach me [@eljojo](https://twitter.com/eljojo).

**Comment by gregkare** [comment]
Hooray! I'm planning to bring a big pasta salad (probably without cheese), sorry people-who-don't-eat-carbs.

**Comment by luki3k5** [comment]
:+1:

**Comment by xamebax** [comment]
Great. :) I'll try to bring something to eat too: cake or salad (vegan), or
- if I get suuuper lazy - some nice fruit.

2014-05-30 18:03 GMT+02:00 Lukasz Lazewski notifications@github.com:

> [image: :+1:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ruby-in-the-park/ruby-in-the-park/issues/4#issuecomment-44667981
> .

## 

Pozdrawiam,
Marta Paciorkowska

**Comment by skade** [comment]
I'll be there and I'll bring... something? I don't know.

**Comment by nanoparsec** [comment]
I will bring some fruit and some frikadellen.
is there someone who can bring a bbq grill?

Ute

2014-05-31 12:17 GMT+02:00 Florian Gilcher notifications@github.com:

> I'll be there and I'll bring... something? I don't know.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ruby-in-the-park/ruby-in-the-park/issues/4#issuecomment-44744496
> .

## 

_--------------_
_nerdbabe_

_Personal Contact Information_
_Email: mail@nerdbabe.de mail@nerdbabe.de_
_Website: nerdbabe.de http://nerdbabe.de_
_Twitter: *nerdbabe
https://mail.google.com/mail/ca/u/0/https//:twitter.com/nerdbabe
*Github:_ NerdBabe https://github.com/NerdBabe

**Comment by ellenkoenig** [comment]
I have other stuff going on at 3pm, but I will try to join later for a bit on if you are still around.

**Comment by eljojo** [comment]
Hi everyone, just updated the issue description with the exact location.
See you all tomorrow at 3 pm!

I'll paste the link here in case you're reading this over email.

We're meeting in the BBQ Area next to the baseball fields.
[Google Maps Link](https://www.google.com/maps/place/52%C2%B028'47.7%22N+13%C2%B024'18.9%22E/@52.4799501,13.4015292,15z/data=!4m2!3m1!1s0x0:0x0) | [Apple Maps Link](http://maps.apple.com/?lsp=7618&sll=52.479917,13.405250&q=52.479917,13.405250)

![dsc_8610](https://cloud.githubusercontent.com/assets/491230/3139000/09919ce4-e8c0-11e3-8add-4da2ee1d7a6c.JPG)

**Comment by eljojo** [comment]
@skade I'm bringing a six pack of Schoferhoffers and I'll try to come up with some sort of food to share.

@NerdBabe we decided with @gregkare to do it in the Grillplatz anyways, in case someone shows up with a BBQ.

@ellenkoenig for sure! If we're not there when you arrive, we might be in the biergarten just next. Call me when you arrive. (my phone is in the issue description)

**Comment by PragTob** [comment]
I'll also show up and bring... stuff. Most likely vegetables/fruits/cookies/something. Or I'll just steal all the food you bring which probably is too much anyways :)

See you!

**Comment by skade** [comment]
I'll be bringing Pita and pastes, olives and some peppers.

**Comment by schultyy** [comment]
I'll bring some drinks like club mate and bionade. I also bought some vegetables and baguette.

**Comment by asaaki** [comment]
I'll bring stuff like snacks:
![ruby-in-the-park](https://cloud.githubusercontent.com/assets/446613/3139753/b0a0322e-e8ee-11e3-91c6-2bea3c0570bd.jpg)

**Comment by nanoparsec** [comment]
awwwwww yummi 💜

Am Samstag, 31. Mai 2014 schrieb Christoph Grabo :

> I'll bring stuff like snacks:
> [image: ruby-in-the-park]
> https://cloud.githubusercontent.com/assets/446613/3139753/b0a0322e-e8ee-11e3-91c6-2bea3c0570bd.jpg
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ruby-in-the-park/ruby-in-the-park/issues/4#issuecomment-44755296
> .

## 

_--------------_
_nerdbabe_

_Personal Contact Information_
_Email: mail@nerdbabe.de mail@nerdbabe.de_
_Website: nerdbabe.de http://nerdbabe.de_
_Twitter: *nerdbabe
https://mail.google.com/mail/ca/u/0/https//:twitter.com/nerdbabe
*Github:_ NerdBabe https://github.com/NerdBabe

**Comment by PragTob** [comment]
so @jalyna will make a "Fladenbrottorte" - whatever that is. But she says it's awesome.

**Comment by gregkare** [comment]
Can someone bring plastic plates and forks? I forgot to and it's now 22:00 on a Saturday. I'll try to find some at a Späti tomorrow but if you have some, bring them. Thanks!

**Comment by sinetris** [comment]
@gregkare I'll go get them. I am close to the Kaisers Supermarket, which should be open until 12pm. Need anything else?

**Comment by asaaki** [comment]
I have some paper plates (hidden under the sausages :-).

**Comment by skade** [comment]
Would anyone mind if we bring a dog? (with leash, obviously)

**Comment by myabc** [comment]
the more the merrier :dog2: :dog: :dog2: :dog: :dog2: :dog:

**Comment by schultyy** [comment]
Yup I bought some. Forgot to mention

**Comment by PragTob** [comment]
I'd love to have Paris there! :dog2: (other dogs welcome as well)

**Comment by gregkare** [comment]
I read that as "Would someone mind bringing a dog?" (I should not read emails when I'm drinking whisky)

**Comment by skade** [comment]
@gregkare That's gross and I felt the need to react! This issue is now tracked as #5.

**Comment by eljojo** [comment]
^ :+1:

**Comment by beatontherat** [comment]
I am a Ruby & Rails über-newbie but I would join if I can make it. Is there anything missing I can bring?

**Comment by eljojo** [comment]
@beatontherat I guess plastic forks and plates are on the list. also blankets are always welcome. regarding food, everything helps :yum:

**Comment by beatontherat** [comment]
@eljojo thanks!

**Comment by stefanozanella** [comment]
@eljojo I guess the BBQ grill it's still missing, oder? Asking so to know what to bring...

**Comment by eljojo** [comment]
@stefanozanella AFAIK nobody's bringing a BBQ.
The question is if people will bring something we can put on the BBQ.

**Comment by stefanozanella** [comment]
@eljojo I bought some vegetarian stuff to be grilled, but I can also just prepare something to be consumed cold. Unfortunately I'm not a lucky BBQ owner, otherwise I'd bring it...

**Comment by skade** [comment]
Anyone bringing [cups](http://www.cups.org)? ;)

**Comment by asaaki** [comment]
Shall we print them? @skade

**Comment by skade** [comment]
@asaaki Sure, I'd like to have the logo on them ;).

**Comment by eljojo** [comment]
I could use some [samba](https://www.samba.org/) too!

**Comment by asaaki** [comment]
I want to have some _[Cuba](https://github.com/soveran/cuba) Libre_ instead.

**Comment by skade** [comment]
The [Padrino](http://it.wikipedia.org/wiki/Il_padrino_%28film%29) doesn't approve.

**Comment by schultyy** [comment]
Can someone bring Sinatra for music?

**Comment by eljojo** [comment]
Everybody! We decided to move the picnic to 
http://goo.gl/maps/hQ8rm

**Comment by asaaki** [comment]
BTW I missed the dog!

**Comment by eljojo** [comment]
Thanks to everyone that attended and to the ones that wanted but couldn't.
See you the next time!
![img_2408_2](https://cloud.githubusercontent.com/assets/491230/3144257/44703614-ea1d-11e3-8492-8f4396577995.jpg)

PS: If you don't want to be included in any picture online, please let me know.

**Comment by PragTob** [comment]
Best conversation I ever had with a tree! Such a nice tree!

**Comment by jalyna** [comment]
find the face :dancers:

**Comment by wordgraphy** [comment]
![photo](https://cloud.githubusercontent.com/assets/734549/3146575/d8362558-ea49-11e3-98dd-7f08fc4ae946.jpg)

**Comment by myabc** [comment]
@PragTob I only just noticed. What type of tree is that? Looks like an AST to me.

**Comment by skade** [comment]
@myabc Pretty sure thats a trie.
