### ISSUE TITLE
Some attendees have weird taste

### ISSUE THREAD

**Issue by skade** [ruby-in-the-park/ruby-in-the-park#5]
See https://github.com/ruby-in-the-park/ruby-in-the-park/issues/4#issuecomment-44760595

**Comment by asaaki** [comment]
I guess it is a cultural thing and we should talk about that while having the picnic with food, drinks and dogs.

**Comment by eljojo** [comment]
![20120608-puppyruntimeerror](https://cloud.githubusercontent.com/assets/491230/3140745/e77514d2-e938-11e3-8498-ce13cd7d8ca6.png)

**Comment by eljojo** [comment]
I missed the [puppy](http://puppylinux.org/main/Overview%20and%20Getting%20Started.htm)
