### ISSUE TITLE
Next picnic?

### ISSUE THREAD

**Issue by nanoparsec** [ruby-in-the-park/ruby-in-the-park#7]
Hey,

should we do a ruby in the park picnic again?

**UPDATE FROM JOJO:**
The picnic is still going in  "Park am Gleisdreieck 2", this Sunday 6th of July.

The exact location is here: [http://goo.gl/maps/mQMVR](http://goo.gl/maps/mQMVR)
The meeting time is 3:00 PM.

**Comment by eljojo** [comment]
I think that's an amazing idea.
What about July 6th?

Even though Tempelhofer feld is great, I'd like to go to a new park (so we get to know them all!)

Any suggestions? cc @malwine

**Comment by gregkare** [comment]
I'll be in France from July 5 to 16 so I'm going to miss this one

**Comment by selfawaresoup** [comment]
Sounds great!

July 6th works for me.

**Comment by sferik** [comment]
July 6 for me too!

**Comment by Malwine** [comment]
I am in for July 6.
There are some really nice parks to test. 
My favorite atm is "Park am Gleisdreieck 2" (Yorckstr.)

**Comment by selfawaresoup** [comment]
"Park am Gleisdreieck" is really beautiful and also has some shade, something that Tempelhof really lacks. It's also easy to reach by public transport (S1, S2, S25, U1, U2)

**Comment by jalyna** [comment]
:+1:

**Comment by asaaki** [comment]
:+1: 

Wow, sounds great so far.
Will try to join.

**Comment by sinetris** [comment]
:thumbsup:

**Comment by ghost** [comment]
I would love to meet you all! I will bring some vegan potato salad and some vegetarian burritos ;)

**Comment by eljojo** [comment]
Either this weekend or the one after I'm going to "Park am Gleisdreieck" to look for a nice spot (anybody feel free to join //cc @gregkare).
I'll update with a nice map and some information as soon as I know it. I'll also prepare an iCal file during the next days.
Finally, I'm going to announce this in the next rug-b anyways in case someone forgets.

**Comment by gregkare** [comment]
Weeeee, I'm in to scout that park, it's actually been on my list for a long time.

By the way talking about good parks, I really like this not so well known, tiny and really cute park: [Körnerpark](http://www.findingberlin.com/koernerpark-neukoelln/) in Neukölln.

**Comment by skade** [comment]
:+1:

**Comment by schultyy** [comment]
:+1:

**Comment by eljojo** [comment]
Hi everyone that is watching this. The picnic is still going.
I'll update the location on saturday and ask @pragtob to retweet it so everyone can see. In case of doubt please check here. I'll update the issue description with my phone number in case of any questions.
I'll also mail in the rug-b mailing list.

BTW: Please bring something to share :)

**Comment by ctrlaltjustine** [comment]
In.

**Comment by selfawaresoup** [comment]
Still in.

**Comment by skade** [comment]
Out :(

**Comment by asaaki** [comment]
What? Why? @skade

**Comment by skade** [comment]
Out of town, nothing serious.

**Comment by asaaki** [comment]
:relieved:

Next time then.

**Comment by xamebax** [comment]
Most probably in, wanted to check out Gleisdreieck for quite some time now!

**Comment by pxlpnk** [comment]
this time I make it!

**Comment by bitboxer** [comment]
I am in! Hooray :dancer: :balloon:

**Comment by eljojo** [comment]
Hi everyone, The exact location of the picnic is going to be: http://goo.gl/maps/mQMVR

In case of questions posts here or contact me (see issue description).

See you tomorrow at 3:00 PM!

**Comment by eljojo** [comment]
![screen shot 2014-07-05 at 17 46 55](https://cloud.githubusercontent.com/assets/491230/3486952/aab86038-045b-11e4-978a-dfc00d2220d8.png)

**Comment by allomov** [comment]
I'll join you! :alien:

**Comment by eljojo** [comment]
Hi everyone, 
We changed the meeting point to http://goo.gl/maps/KfawJ

**Comment by eljojo** [comment]
Thanks to everyone who attended the picnic, had lots of fun!
Already looking forward for the next one

![Photo by @NerdBabe](https://pbs.twimg.com/media/Br3xaFdCQAAiNJG.jpg)

I collected some tweets :)
https://twitter.com/SaltineJustine/status/485811032624201730
https://twitter.com/nerdbabe/status/485809894768275456
https://twitter.com/nerdbabe/status/485771331880091648
https://twitter.com/lnwdr/status/485813870356086784
https://twitter.com/neinasaservice/status/485852332119576576

**Comment by bitboxer** [comment]
<a href="https://www.flickr.com/photos/wannawork/14597054862" title="20140706-P7060008.jpg by Bodo Tasche, on Flickr"><img src="https://farm3.staticflickr.com/2897/14597054862_98be9e69cc.jpg" width="500" height="375" alt="20140706-P7060008.jpg"></a>

<a href="https://www.flickr.com/photos/wannawork/14594413731" title="20140706-P7060005.jpg by Bodo Tasche, on Flickr"><img src="https://farm6.staticflickr.com/5562/14594413731_74dd552238.jpg" width="500" height="375" alt="20140706-P7060005.jpg"></a>

<a href="https://www.flickr.com/photos/wannawork/14595774944" title="20140706-P7060004.jpg by Bodo Tasche, on Flickr"><img src="https://farm4.staticflickr.com/3836/14595774944_1209946409.jpg" width="500" height="375" alt="20140706-P7060004.jpg"></a>
